### ISSUE TITLE
The method '_greaterThanFromInteger' was called on null.

### ISSUE THREAD

**Issue by a7me63azzab** [thangmam/smoothratingbar#1]
> When trying to use this package i get this error

```
I/flutter (11109): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (11109): The following NoSuchMethodError was thrown building SmoothStarRating(dirty):
I/flutter (11109): The method '_greaterThanFromInteger' was called on null.
I/flutter (11109): Receiver: null
I/flutter (11109): Tried calling: _greaterThanFromInteger(0)
I/flutter (11109): When the exception was thrown, this was the stack:
I/flutter (11109): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (11109): #1      int.> (dart:core/runtime/libintegers.dart:71:18)
I/flutter (11109): #2      int.>= (dart:core/runtime/libintegers.dart:76:37)
I/flutter (11109): #3      SmoothStarRating.buildStar (package:shopapp_tut/src/widgets/star_rating.dart:25:15)
I/flutter (11109): #4      SmoothStarRating.build.<anonymous closure> (package:shopapp_tut/src/widgets/star_rating.dart:74:37)
I/flutter (11109): #5      new List.generate (dart:core/list.dart:162:28)
I/flutter (11109): #6      SmoothStarRating.build (package:shopapp_tut/src/widgets/star_rating.dart:73:25)
I/flutter (11109): #7      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
I/flutter (11109): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (11109): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (11109): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (11109): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (11109): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (11109): #13     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:3
```

**Comment by thangmam** [comment]
What is your flutter version ?Also just check and make sure you update to the latest version of this library ?Can you show me the code where you initialize the smoothratingbar?

**Comment by samuelfre** [comment]
I had issue with this package too. anyone help us

**Comment by thangmam** [comment]
I have looked in this and this issue does not seem to concern the library.Try verifying the issue by isolating the problem.You can try adding the library in a fresh project and see if the problem exists.If it does,let me know .I will close this issue for now.

**Comment by UnnikrishnanBhargavakurup** [comment]
I'm also facing the same issue,  my flutter version is `environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"` Please look into this.

**Comment by shalaby** [comment]
this problem occurs due to using a non intialized variable => null:
```dart
SmoothStarRating(
          allowHalfRating: false,
          onRatingChanged: (v) {
            rating = v;
            setState(() {});
          },
          starCount: 5,
          rating: rating, // <----------- rating = null
          size: 40.0,
          color: Colors.green,
          borderColor: Colors.green,
        )
```
to fix this either initialize the variable like:
```dart
double rating = 0;
```
or in the widget block:
```dart
rating: rating ?? 0 // <------------ rating
```
and @thangmam Thank you for this great plugin 👍

**Comment by thangmam** [comment]
@shalaby  Welcome and thanks for clarifying the error.I have updated the repository and added an assert to check for rating nullability which will throw more meaningful exceptions
